### ISSUE TITLE
Agents do scale up only by settings capability to "1"

### ISSUE THREAD

**Issue by 24mu13** [MShekow/azure-pipelines-k8s-agent-scaler#50]
If you have **minCount** set to 0, and you don't specify capabilities, Azure Pipeline will say that _there are no agents available which satisfy the job requirements_.

Everything is working fine if you set the required capability to "1", e.g. `java: "1"`. Otherwise, any other combination like additional capabilities or richer values will not work. Here below an example:

```yaml
podsWithCapabilities:
  - capabilities:
      java: "/usr/bin/java"
      JDK: "/usr/bin/javac"
```
